### ISSUE TITLE
Error running on windows 10

### ISSUE THREAD

**Issue by jasjuang** [brianzq/att-bill-splitter#15]
I ran it successfully on Ubuntu but the below error shows up for Windows 10.

```
pip install att-bill-splitter
att-split-bill -l 0
```

after inputting the login credentials for att it shows

```
Traceback (most recent call last):
  File "C:\Python27\Scripts\att-split-bill-script.py", line 9, in <module>
    load_entry_point('att-bill-splitter==0.4.6', 'console_scripts', 'att-split-bill')()
  File "c:\python27\lib\site-packages\attbillsplitter\entrypoints.py", line 10, in split_bill
    run_split_bill()
  File "c:\python27\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\attbillsplitter\main.py", line 528, in run_split_bill
    splitter.run(lag, force)
  File "c:\python27\lib\site-packages\attbillsplitter\main.py", line 486, in run
    if not self.login():
  File "c:\python27\lib\site-packages\attbillsplitter\main.py", line 110, in login
    print('\U000025B6  Login started...')
  File "c:\python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u25b6' in position 0: character maps to <undefined>
```

**Comment by jasjuang** [comment]
solved by #17
